import {
  ACTION_PLAN_PROMPT_NAME,
  ACTION_PLAN_PROMPT_TEMPLATE_HASH,
  ACTION_PLAN_PROMPT_VERSION,
  ACTION_PLAN_RESPONSE_SCHEMA_VERSION,
} from "@/src/server/modules/action-plans/prompt-contract";
import {
  GAP_PROMPT_NAME,
  GAP_PROMPT_TEMPLATE_HASH,
  GAP_PROMPT_VERSION,
  GAP_RESPONSE_SCHEMA_VERSION,
} from "../../prompt-contract";
import type {
  GapAnalysisReleaseDefinition,
  GapQuestionDefinition,
  GapRequirementDefinition,
  LocalizedText,
} from "../types";

const optionLabels = {
  fully_implemented: {
    de: "Vollständig umgesetzt",
    en: "Fully implemented",
  },
  partially_implemented: {
    de: "Teilweise umgesetzt",
    en: "Partially implemented",
  },
  not_implemented: { de: "Nicht umgesetzt", en: "Not implemented" },
  unsure: { de: "Unsicher", en: "Unsure" },
  not_applicable: { de: "Nicht relevant", en: "Not applicable" },
} satisfies Record<string, LocalizedText>;

const questions: GapQuestionDefinition[] = [
  q(
    1,
    "gap.governance.security_owner",
    "Gibt es eine klar benannte Person oder ein Team, das für IT-Sicherheit verantwortlich ist?",
    "Is a person or team clearly designated as responsible for IT security?",
    "Zum Beispiel Informationssicherheitsbeauftragte, IT-Leitung oder externer Dienstleister. Zuständigkeit und Vertretung sollten dokumentiert sein.",
    "For example, an information security officer, IT management, or an external provider. Responsibilities and deputies should be documented.",
    ["de_bsig.section_38_1", "eu_nis2.article_20_1"],
    "high",
  ),
  q(
    2,
    "gap.governance.management_oversight",
    "Beschließt und überwacht die Geschäftsleitung wichtige Maßnahmen zur IT-Sicherheit?",
    "Does management approve and oversee important IT security measures?",
    "Zum Beispiel regelmäßiger Sicherheitsbericht, Freigabe von Maßnahmen und Budget sowie dokumentierte Entscheidungen.",
    "For example, regular security reports, approval of measures and budgets, and documented decisions.",
    ["de_bsig.section_38_1", "eu_nis2.article_20_1"],
    "high",
  ),
  q(
    3,
    "gap.governance.management_training",
    "Nimmt die Geschäftsleitung regelmäßig an Schulungen zu Cyberrisiken und IT-Sicherheit teil?",
    "Does management regularly attend training on cyber risks and IT security?",
    "Schulungen sollten wiederholt stattfinden und zur Rolle der Geschäftsleitung passen.",
    "Training should be repeated and appropriate to management's role.",
    ["de_bsig.section_38_3", "eu_nis2.article_20_2"],
    "high",
  ),
  q(
    4,
    "gap.risk.written_analysis",
    "Gibt es eine schriftliche Risikoanalyse für IT-Systeme, Daten und wichtige Geschäftsprozesse?",
    "Is there a written risk analysis for IT systems, data, and important business processes?",
    "Die Analyse sollte Bedrohungen, Schwachstellen, mögliche Schäden und vorhandene Schutzmaßnahmen enthalten.",
    "The analysis should cover threats, vulnerabilities, potential harm, and existing safeguards.",
    ["de_bsig.section_30_2_1", "eu_nis2.article_21_2_a"],
    "high",
  ),
  q(
    5,
    "gap.risk.analysis_updates",
    "Wird die Risikoanalyse regelmäßig und nach größeren Änderungen oder Sicherheitsvorfällen aktualisiert?",
    "Is the risk analysis updated regularly and after major changes or security incidents?",
    "Zum Beispiel mindestens jährlich sowie nach neuen Systemen, Umzügen, größeren Dienstleisterwechseln oder Vorfällen.",
    "For example, at least annually and after new systems, relocations, major provider changes, or incidents.",
    [
      "de_bsig.section_30_1",
      "de_bsig.section_30_2_1",
      "eu_nis2.article_21_1",
      "eu_nis2.article_21_2",
    ],
    "high",
  ),
  q(
    6,
    "gap.risk.critical_dependencies",
    "Ist bekannt, welche Geschäftsprozesse, IT-Systeme, Daten und Dienstleister für den Betrieb besonders wichtig sind?",
    "Is it known which business processes, IT systems, data, and providers are particularly important to operations?",
    "Gemeint sind Abhängigkeiten, deren Ausfall den Betrieb stark beeinträchtigen würde.",
    "This means dependencies whose failure would severely disrupt operations.",
    [
      "de_bsig.section_30_1",
      "de_bsig.section_30_2_1",
      "de_bsig.section_30_2_9",
      "eu_nis2.article_21_1",
      "eu_nis2.article_21_2",
    ],
    "high",
  ),
  q(
    7,
    "gap.risk.asset_inventory",
    "Gibt es eine aktuelle Übersicht über Geräte, Programme, Cloud-Dienste, Benutzerkonten und wichtige Daten?",
    "Is there an up-to-date inventory of devices, software, cloud services, user accounts, and important data?",
    "Zum Beispiel Inventarliste mit Verantwortlichen, Standort, Version, Schutzbedarf und Lebenszyklus.",
    "For example, an inventory with owners, location, version, protection needs, and lifecycle.",
    ["de_bsig.section_30_2_9", "eu_nis2.article_21_2_i"],
    "medium",
  ),
  q(
    8,
    "gap.iam.least_privilege",
    "Erhalten Mitarbeitende nur die Zugriffsrechte, die sie für ihre Aufgaben benötigen, und werden diese Rechte regelmäßig geprüft?",
    "Do employees receive only the access rights needed for their work, and are those rights reviewed regularly?",
    "Prinzip der geringsten Rechte; besonders wichtig bei Administrationsrechten und sensiblen Daten.",
    "Apply least privilege, especially for administrative access and sensitive data.",
    ["de_bsig.section_30_2_9", "eu_nis2.article_21_2_i"],
    "high",
  ),
  q(
    9,
    "gap.iam.joiner_mover_leaver",
    "Werden Zugänge bei einem Stellenwechsel oder Austritt schnell angepasst oder gesperrt?",
    "Are accounts promptly adjusted or disabled when a person changes roles or leaves?",
    "Es sollte ein klarer Eintritts-, Wechsel- und Austrittsprozess zwischen Personalbereich und IT bestehen.",
    "A clear joiner, mover, and leaver process should connect HR and IT.",
    ["de_bsig.section_30_2_9", "eu_nis2.article_21_2_i"],
    "high",
  ),
  q(
    10,
    "gap.iam.multi_factor_authentication",
    "Wird für besonders wichtige Zugänge, Administratorenkonten und Fernzugriffe eine Multi-Faktor-Authentifizierung genutzt?",
    "Is multi-factor authentication used for particularly important access, administrator accounts, and remote access?",
    "Zum Beispiel Passwort plus Authenticator-App oder Sicherheitsschlüssel.",
    "For example, a password plus an authenticator app or security key.",
    ["de_bsig.section_30_2_10", "eu_nis2.article_21_2_j"],
    "high",
  ),
  q(
    11,
    "gap.incident.written_response_plan",
    "Gibt es einen schriftlichen Plan für den Umgang mit Cyberangriffen und IT-Sicherheitsvorfällen?",
    "Is there a written plan for handling cyberattacks and IT security incidents?",
    "Der Plan sollte Erkennung, Eindämmung, Beweissicherung, Wiederherstellung und Nachbereitung abdecken.",
    "The plan should cover detection, containment, evidence preservation, recovery, and lessons learned.",
    ["de_bsig.section_30_2_2", "eu_nis2.article_21_2_b"],
    "high",
  ),
  q(
    12,
    "gap.incident.roles_and_contacts",
    "Sind Rollen, Vertretungen und Kontaktwege für einen Sicherheitsvorfall klar festgelegt?",
    "Are roles, deputies, and contact paths for a security incident clearly defined?",
    "Zum Beispiel Geschäftsleitung, IT, Datenschutz, Kommunikation, externer IT-Dienstleister und Behördenkontakt.",
    "For example, management, IT, data protection, communications, an external IT provider, and authority contacts.",
    ["de_bsig.section_30_2_2", "eu_nis2.article_21_2_b"],
    "high",
  ),
  q(
    13,
    "gap.incident.detection_and_records",
    "Kann das Unternehmen Sicherheitsvorfälle erkennen, bewerten und nachvollziehbar dokumentieren?",
    "Can the organization detect, assess, and document security incidents traceably?",
    "Zum Beispiel Protokollierung, Warnmeldungen, Ticket-System und Kriterien für Schweregrad und Auswirkungen.",
    "For example, logging, alerts, ticketing, and criteria for severity and impact.",
    [
      "de_bsig.section_30_2_2",
      "de_bsig.section_30_2_6",
      "eu_nis2.article_21_2_b",
      "eu_nis2.article_21_2_f",
    ],
    "high",
  ),
  q(
    14,
    "gap.incident.reporting_timeline",
    "Gibt es einen Ablauf, um erhebliche Sicherheitsvorfälle fristgerecht zu melden: frühe Erstmeldung innerhalb von 24 Stunden, Meldung innerhalb von 72 Stunden und Abschlussmeldung innerhalb eines Monats?",
    "Is there a process for reporting significant security incidents on time: an early warning within 24 hours, a notification within 72 hours, and a final report within one month?",
    "Der Prozess sollte Zuständigkeiten, Entscheidungskriterien, benötigte Informationen und Vertretungen enthalten.",
    "The process should define responsibilities, decision criteria, required information, and deputies.",
    ["de_bsig.section_32", "eu_nis2.article_23"],
    "high",
  ),
  q(
    15,
    "gap.continuity.regular_backups",
    "Werden wichtige Daten und Systeme regelmäßig gesichert?",
    "Are important data and systems backed up regularly?",
    "Häufigkeit und Umfang sollten zum möglichen Schaden bei Datenverlust passen.",
    "Frequency and scope should reflect the potential harm from data loss.",
    ["de_bsig.section_30_2_3", "eu_nis2.article_21_2_c"],
    "high",
  ),
  q(
    16,
    "gap.continuity.protected_backups",
    "Sind Backups vor Veränderung oder Löschung geschützt und getrennt vom normalen System gespeichert?",
    "Are backups protected from modification or deletion and stored separately from normal systems?",
    "Zum Beispiel offline, unveränderbar oder in einem getrennten Konto bzw. Standort.",
    "For example, offline, immutable, or in a separate account or location.",
    ["de_bsig.section_30_2_3", "eu_nis2.article_21_2_c"],
    "high",
  ),
  q(
    17,
    "gap.continuity.restore_tests",
    "Wird regelmäßig getestet, ob Daten und Systeme aus den Backups wirklich wiederhergestellt werden können?",
    "Is it tested regularly whether data and systems can actually be restored from backups?",
    "Ein vorhandenes Backup reicht nicht; die Wiederherstellung sollte praktisch getestet und dokumentiert werden.",
    "Having a backup is not enough; restoration should be tested in practice and documented.",
    [
      "de_bsig.section_30_2_3",
      "de_bsig.section_30_2_6",
      "eu_nis2.article_21_2_c",
      "eu_nis2.article_21_2_f",
    ],
    "high",
  ),
  q(
    18,
    "gap.continuity.recovery_plan",
    "Gibt es einen Notfall- und Wiederanlaufplan, der wichtige Prozesse, Zuständigkeiten und Wiederherstellungsziele festlegt?",
    "Is there an emergency and recovery plan defining important processes, responsibilities, and recovery objectives?",
    "Zum Beispiel maximale Ausfallzeit, tolerierbarer Datenverlust, Ersatzlösungen und Krisenorganisation.",
    "For example, maximum downtime, tolerable data loss, alternative solutions, and crisis organization.",
    ["de_bsig.section_30_2_3", "eu_nis2.article_21_2_c"],
    "high",
  ),
  q(
    19,
    "gap.supply_chain.provider_risk",
    "Sind die wichtigsten IT-Dienstleister und Lieferanten bekannt und nach ihrem Sicherheitsrisiko bewertet?",
    "Are the most important IT providers and suppliers known and assessed for security risk?",
    "Besonders relevant sind Cloud, Hosting, Software, Fernwartung, Managed Services und zentrale Hardwarelieferanten.",
    "Cloud, hosting, software, remote maintenance, managed services, and key hardware suppliers are particularly relevant.",
    [
      "de_bsig.section_30_2_4",
      "eu_nis2.article_21_2_d",
      "eu_nis2.article_21_3",
    ],
    "high",
  ),
  q(
    20,
    "gap.supply_chain.contract_requirements",
    "Enthalten Verträge mit wichtigen Dienstleistern klare Anforderungen zur IT-Sicherheit und zu Sicherheitsvorfällen?",
    "Do contracts with important providers contain clear requirements for IT security and security incidents?",
    "Zum Beispiel Meldewege, Reaktionszeiten, Zugriffsrechte, Unterauftragnehmer, Backups und Beendigung des Vertrags.",
    "For example, reporting paths, response times, access rights, subcontractors, backups, and contract termination.",
    [
      "de_bsig.section_30_2_4",
      "eu_nis2.article_21_2_d",
      "eu_nis2.article_21_3",
    ],
    "medium",
  ),
  q(
    21,
    "gap.supply_chain.provider_contingency",
    "Gibt es einen Ablauf für Ausfälle, Sicherheitsprobleme oder den Wechsel eines wichtigen Dienstleisters?",
    "Is there a process for outages, security problems, or replacing an important provider?",
    "Zum Beispiel Ausweichlösung, Datenrückgabe, Sperrung von Zugängen und sichere Vertragsbeendigung.",
    "For example, an alternative solution, data return, access revocation, and secure contract termination.",
    [
      "de_bsig.section_30_2_3",
      "de_bsig.section_30_2_4",
      "eu_nis2.article_21_2_c",
      "eu_nis2.article_21_2_d",
    ],
    "medium",
  ),
  q(
    22,
    "gap.secure_systems.security_by_design",
    "Werden Sicherheitsanforderungen bereits beim Kauf, bei der Entwicklung und bei Änderungen von IT-Systemen berücksichtigt?",
    "Are security requirements considered when purchasing, developing, and changing IT systems?",
    "Zum Beispiel Mindestanforderungen, Freigaben, sichere Einstellungen, Tests und dokumentierte Änderungen.",
    "For example, minimum requirements, approvals, secure configurations, tests, and documented changes.",
    ["de_bsig.section_30_2_5", "eu_nis2.article_21_2_e"],
    "high",
  ),
  q(
    23,
    "gap.secure_systems.patch_management",
    "Gibt es einen geregelten Prozess, um Sicherheitsupdates und Patches zeitnah einzuspielen?",
    "Is there a controlled process for applying security updates and patches promptly?",
    "Der Prozess sollte Verantwortliche, Prioritäten, Testverfahren und Fristen für kritische Lücken festlegen.",
    "The process should define owners, priorities, testing, and deadlines for critical vulnerabilities.",
    ["de_bsig.section_30_2_5", "eu_nis2.article_21_2_e"],
    "high",
  ),
  q(
    24,
    "gap.secure_systems.vulnerability_management",
    "Gibt es einen geregelten Prozess, um Schwachstellen zu finden, zu bewerten, zu beheben und gegebenenfalls offenzulegen?",
    "Is there a controlled process for finding, assessing, remediating, and, where appropriate, disclosing vulnerabilities?",
    "Zum Beispiel Scans, Meldemöglichkeit, Risikobewertung, Behebung und Dokumentation.",
    "For example, scans, a reporting channel, risk assessment, remediation, and documentation.",
    ["de_bsig.section_30_2_5", "eu_nis2.article_21_2_e"],
    "high",
  ),
  q(
    25,
    "gap.assurance.effectiveness_reviews",
    "Wird regelmäßig geprüft, ob die eingeführten Sicherheitsmaßnahmen wirksam sind?",
    "Is the effectiveness of implemented security measures reviewed regularly?",
    "Zum Beispiel interne Kontrollen, Audits, Schwachstellenscans, Wiederherstellungstests oder Übungen.",
    "For example, internal controls, audits, vulnerability scans, restoration tests, or exercises.",
    ["de_bsig.section_30_2_6", "eu_nis2.article_21_2_f"],
    "high",
  ),
  q(
    26,
    "gap.assurance.remediation_tracking",
    "Werden erkannte Lücken mit Verantwortlichen, Fristen und Umsetzungsnachweisen verfolgt?",
    "Are identified gaps tracked with owners, deadlines, and evidence of implementation?",
    "Die Maßnahmenliste sollte priorisiert, regelmäßig aktualisiert und von der Leitung nachverfolgt werden.",
    "The action list should be prioritized, updated regularly, and monitored by management.",
    ["de_bsig.section_30_1", "de_bsig.section_30_2_6", "eu_nis2.article_21_4"],
    "high",
  ),
  q(
    27,
    "gap.awareness.employee_training",
    "Erhalten Mitarbeitende regelmäßig verständliche Schulungen zu Phishing, Passwörtern, Datenschutz und sicherem Arbeiten?",
    "Do employees regularly receive understandable training on phishing, passwords, data protection, and secure working?",
    "Schulungen sollten wiederholt, rollenbezogen und möglichst durch Übungen ergänzt werden.",
    "Training should be repeated, role-based, and supplemented by exercises where possible.",
    ["de_bsig.section_30_2_7", "eu_nis2.article_21_2_g"],
    "medium",
  ),
  q(
    28,
    "gap.awareness.cyber_hygiene_rules",
    "Gibt es verbindliche Grundregeln für sicheres Arbeiten, zum Beispiel zu Passwörtern, Updates, E-Mail, mobilen Geräten und Homeoffice?",
    "Are there binding basic rules for secure working, for example on passwords, updates, email, mobile devices, and remote work?",
    "Die Regeln sollten leicht auffindbar, verständlich und technisch unterstützt sein.",
    "The rules should be easy to find, understandable, and supported by technical controls.",
    ["de_bsig.section_30_2_7", "eu_nis2.article_21_2_g"],
    "medium",
  ),
  q(
    29,
    "gap.protection.encryption",
    "Werden sensible Daten und wichtige Verbindungen angemessen verschlüsselt?",
    "Are sensitive data and important connections encrypted appropriately?",
    "Zum Beispiel Festplatten, Backups, mobile Geräte, Webseiten, Fernzugriffe und Datenaustausch.",
    "For example, disks, backups, mobile devices, websites, remote access, and data exchange.",
    ["de_bsig.section_30_2_8", "eu_nis2.article_21_2_h"],
    "medium",
  ),
  q(
    30,
    "gap.protection.secure_communications",
    "Gibt es sichere Kommunikationswege für den normalen Betrieb und für Notfälle, die auch bei einem Ausfall der üblichen Systeme genutzt werden können?",
    "Are secure communication channels available for normal operations and emergencies, including when usual systems fail?",
    "Zum Beispiel abgesicherte Sprach-, Video- und Textkommunikation sowie ein alternativer Notfallkanal.",
    "For example, secured voice, video, and text communication plus an alternative emergency channel.",
    ["de_bsig.section_30_2_10", "eu_nis2.article_21_2_j"],
    "medium",
  ),
  q(
    31,
    "gap.protection.physical_security",
    "Sind wichtige IT-Systeme und Räume gegen unbefugten Zutritt, Stromausfall, Feuer, Wasser und andere physische Gefahren geschützt?",
    "Are important IT systems and rooms protected against unauthorized access, power failure, fire, water, and other physical hazards?",
    "Der Schutz sollte zur Bedeutung des Systems passen, zum Beispiel Zutrittskontrolle, USV, Brandschutz und geeigneter Standort.",
    "Protection should match the system's importance, for example access control, UPS, fire protection, and suitable location.",
    ["de_bsig.section_30_1", "de_bsig.section_30_2", "eu_nis2.article_21_2"],
    "medium",
  ),
];

const requirements: GapRequirementDefinition[] = [
  category(
    1,
    "NIS2-GOV-01",
    "Building2",
    "Responsibility and organization",
    "Verantwortung und Organisation",
    "The organization assigns and documents information-security responsibility, and management approves, oversees, and receives appropriate training for cybersecurity risk-management measures.",
    "Die Organisation weist die Verantwortung für Informationssicherheit nachvollziehbar zu; die Geschäftsleitung beschließt und überwacht die Maßnahmen zum Umgang mit Cybersicherheitsrisiken und nimmt an geeigneten Schulungen teil.",
    [1, 2, 3],
    "high",
  ),
  category(
    2,
    "NIS2-RISK-02",
    "ShieldAlert",
    "Risks and overview",
    "Risiken und Überblick",
    "The organization maintains an up-to-date, documented risk analysis and an overview of critical processes, systems, data, services, accounts, and dependencies.",
    "Die Organisation hält eine aktuelle, dokumentierte Risikoanalyse sowie einen Überblick über kritische Prozesse, Systeme, Daten, Dienste, Konten und Abhängigkeiten vor.",
    [4, 5, 6, 7],
    "high",
  ),
  category(
    3,
    "NIS2-IAM-03",
    "KeyRound",
    "Access and personnel",
    "Zugriffe und Personal",
    "Access rights follow least privilege throughout personnel changes, with strong authentication for sensitive, administrative, and remote access.",
    "Zugriffsrechte folgen während des gesamten Personalzyklus dem Prinzip der geringsten Rechte; sensible, administrative und entfernte Zugriffe werden stark authentifiziert.",
    [8, 9, 10],
    "high",
  ),
  category(
    4,
    "NIS2-IR-04",
    "Siren",
    "Security incidents and reporting",
    "Sicherheitsvorfälle und Meldung",
    "The organization can prepare for, detect, document, contain, recover from, and report significant security incidents within applicable deadlines.",
    "Die Organisation kann erhebliche Sicherheitsvorfälle vorbereiten, erkennen, dokumentieren, eindämmen, bewältigen und innerhalb der geltenden Fristen melden.",
    [11, 12, 13, 14],
    "high",
  ),
  category(
    5,
    "NIS2-BC-05",
    "DatabaseBackup",
    "Backups and emergency preparedness",
    "Backups und Notfallvorsorge",
    "Important data and systems are backed up securely and restorably, supported by tested continuity and recovery objectives and responsibilities.",
    "Wichtige Daten und Systeme werden sicher und wiederherstellbar gesichert; getestete Notfall- und Wiederanlaufziele sowie Zuständigkeiten unterstützen die Kontinuität.",
    [15, 16, 17, 18],
    "high",
  ),
  category(
    6,
    "NIS2-SC-06",
    "Link",
    "Supply chain",
    "Lieferkette",
    "The organization identifies and assesses important suppliers, sets contractual security expectations, and prepares for provider incidents, outages, and exit.",
    "Die Organisation identifiziert und bewertet wichtige Lieferanten, vereinbart Sicherheitsanforderungen und bereitet sich auf Vorfälle, Ausfälle und den Anbieterwechsel vor.",
    [19, 20, 21],
    "high",
  ),
  category(
    7,
    "NIS2-VM-07",
    "Bug",
    "Secure systems and vulnerabilities",
    "Sichere Systeme und Schwachstellen",
    "Security is integrated into acquisition, development, and change, with controlled patch and vulnerability management throughout system lifecycles.",
    "Sicherheit wird in Beschaffung, Entwicklung und Änderungen integriert; Patches und Schwachstellen werden über den Systemlebenszyklus geregelt behandelt.",
    [22, 23, 24],
    "high",
  ),
  category(
    8,
    "NIS2-ASSURE-08",
    "ClipboardCheck",
    "Effectiveness review",
    "Wirksamkeitsprüfung",
    "The organization reviews whether security measures work and tracks identified deficiencies to accountable, evidenced, and timely remediation.",
    "Die Organisation prüft die Wirksamkeit ihrer Sicherheitsmaßnahmen und verfolgt erkannte Lücken verantwortlich, fristgerecht und mit Umsetzungsnachweisen.",
    [25, 26],
    "high",
  ),
  category(
    9,
    "NIS2-AWARE-09",
    "GraduationCap",
    "Training and cyber hygiene",
    "Schulung und Cyberhygiene",
    "Personnel receive recurring, role-appropriate awareness training and follow accessible, binding cyber-hygiene rules.",
    "Beschäftigte erhalten wiederkehrende, rollenbezogene Sensibilisierung und befolgen zugängliche, verbindliche Regeln zur Cyberhygiene.",
    [27, 28],
    "medium",
  ),
  category(
    10,
    "NIS2-PROTECT-10",
    "LockKeyhole",
    "Encryption, communication, and physical protection",
    "Verschlüsselung, Kommunikation und physischer Schutz",
    "The organization applies appropriate encryption, resilient secure communications, and physical and environmental protection to important systems and data.",
    "Die Organisation schützt wichtige Systeme und Daten durch angemessene Verschlüsselung, ausfallsichere Kommunikation sowie physischen und umgebungsbezogenen Schutz.",
    [29, 30, 31],
    "medium",
  ),
];

export const guidedV6GapRelease: GapAnalysisReleaseDefinition = {
  releaseCode: "nis2-gap",
  versionLabel: "guided-v6",
  title: { de: "NIS2-Gap-Analyse", en: "NIS2 gap analysis" },
  compatibleCheck: {
    checkCode: "nis2_applicability",
    versionLabel: "2026-v2",
  },
  requiredCorpusFamilies: ["nis2-eu-primary", "nis2-de-primary"],
  defaultLocale: "de",
  prompt: {
    name: GAP_PROMPT_NAME,
    version: GAP_PROMPT_VERSION,
    templateHash: GAP_PROMPT_TEMPLATE_HASH,
    responseSchemaVersion: GAP_RESPONSE_SCHEMA_VERSION,
  },
  actionPlanPrompt: {
    name: ACTION_PLAN_PROMPT_NAME,
    version: ACTION_PLAN_PROMPT_VERSION,
    templateHash: ACTION_PLAN_PROMPT_TEMPLATE_HASH,
    responseSchemaVersion: ACTION_PLAN_RESPONSE_SCHEMA_VERSION,
  },
  evaluator: { kind: "nis2_gap_category_v1", version: 1 },
  questionnaire: {
    code: "nis2_gap_guided",
    title: {
      de: "Fragen zur NIS2-Umsetzung",
      en: "Questions about NIS2 implementation",
    },
    questions,
  },
  requirementSet: {
    code: "nis2_gap_categories",
    title: {
      de: "NIS2-Sicherheitsanforderungen",
      en: "NIS2 security requirements",
    },
    versionLabel: "guided-v6",
    requirements,
  },
};

function q(
  sourceNumber: number,
  stableKey: string,
  de: string,
  en: string,
  helpDe: string,
  helpEn: string,
  legalProvisionKeys: string[],
  sourcePriority: NonNullable<GapQuestionDefinition["sourcePriority"]>,
): GapQuestionDefinition {
  return {
    stableKey,
    sourceNumber,
    sourcePriority,
    position: sourceNumber * 10,
    text: { de, en },
    help: { de: helpDe, en: helpEn },
    required: true,
    answerType: "single_choice",
    legalProvisionKeys,
    options: Object.entries(optionLabels).map(
      ([stableValue, label], index) => ({
        stableValue,
        position: (index + 1) * 10,
        label,
      }),
    ),
  };
}

function category(
  position: number,
  code: string,
  icon: GapRequirementDefinition["icon"],
  en: string,
  de: string,
  requirementTextEn: string,
  requirementTextDe: string,
  questionNumbers: number[],
  criticality: GapRequirementDefinition["criticality"],
): GapRequirementDefinition {
  return {
    code,
    versionLabel: "guided-v6",
    icon,
    position,
    criticality,
    title: { de, en },
    requirementText: { de: requirementTextDe, en: requirementTextEn },
    legalReferences: [],
    questionStableKeys: questionNumbers.map(
      (number) => requireQuestion(number).stableKey,
    ),
    applicableOutcomeCodes: ["essential_entity", "important_entity"],
  };
}

function requireQuestion(sourceNumber: number) {
  const question = questions.find(
    (candidate) => candidate.sourceNumber === sourceNumber,
  );
  if (!question)
    throw new Error(`Missing guided-v6 source question ${sourceNumber}`);
  return question;
}
