import * as z from "zod";
import { paginationQuerySchema } from "@/src/contracts/common/pagination";
import { auditQuerySchema } from "@/src/contracts/audit";
import { legalSourceMonitorScheduleSchema } from "./legal-source-monitor-schedule";
export { legalSourceMonitorScheduleSchema } from "./legal-source-monitor-schedule";
export const platformJobsQuerySchema = paginationQuerySchema.extend({ kind: z.string().trim().min(1).max(100).optional(), state: z.enum(["queued", "running", "cancellation_requested", "succeeded", "failed", "cancelled"]).optional() });
export const platformAuditQuerySchema = auditQuerySchema;
export const corpusListQuerySchema = paginationQuerySchema.extend({ q: z.string().trim().min(1).max(200).optional() });
export const processingGenerationQuerySchema = z.object({ previewLimit: z.coerce.number().int().min(1).max(100).default(20) });
export const platformAdministratorGrantSchema = z.object({ userId: z.uuid(), reason: z.string().trim().min(1).max(1000) });
export const reasonSchema = z.object({ reason: z.string().trim().min(1).max(2000) });
export const corpusFamilyCreateSchema = z.object({ code: z.string().trim().min(1), frameworkCode: z.string().trim().min(1), jurisdictionCode: z.string().trim().min(1), title: z.string().trim().min(1) });
export const corpusFamilyUpdateSchema = z.object({ title: z.string().trim().min(1).max(500), archived: z.boolean().optional() });
export const legalSourceCreateSchema = z.object({ familyId: z.uuid(), stableCode: z.string().trim().min(1), title: z.string().trim().min(1), sourceKind: z.string().trim().min(1), authorityTier: z.enum(["primary_authority", "official_guidance", "curated_secondary"]), canonicalPublisher: z.string().trim().min(1), legalInstrumentId: z.uuid().optional(), legalProvisionId: z.uuid().optional() });
export const legalSourceUpdateSchema = z.object({ title: z.string().trim().min(1), canonicalPublisher: z.string().trim().min(1) });
export const legalUploadSessionSchema = z.object({ fileName: z.string().trim().min(1), mimeType: z.string().trim().min(1), size: z.number().int().positive(), sha256: z.string().regex(/^[a-f0-9]{64}$/i).optional() });
export const legalUploadCompleteSchema = z.object({ sourceId: z.uuid(), existingVersionId: z.uuid().optional(), versionLabel: z.string().trim().min(1), officialIdentifier: z.string().optional(), upstreamUrl: z.url().optional(), effectiveFrom: z.string().date().optional(), effectiveTo: z.string().date().optional(), language: z.string().trim().min(2), translationStatus: z.enum(["official", "reviewed_internal", "machine_assisted"]), authoritativeRenditionId: z.uuid().optional(), duplicateAcknowledged: z.boolean().optional() });
export const legalUrlImportSchema = z.object({ exactUrl: z.url(), versionLabel: z.string().trim().min(1), officialIdentifier: z.string().optional(), effectiveFrom: z.string().date().optional(), effectiveTo: z.string().date().optional(), language: z.string().trim().min(2) });
export const corpusReleaseCreateSchema = z.object({ familyId: z.uuid(), versionLabel: z.string().trim().min(1) });
export const corpusReleaseMembersSchema = z.object({ members: z.array(z.object({ sourceVersionId: z.uuid(), renditionId: z.uuid(), processingGenerationId: z.uuid() })) });
export const corpusActivateSchema = z.object({ emergencyOverrideReason: z.string().trim().min(1).max(2000).optional() });
export const corpusMonitorCreateSchema = z.object({ sourceId: z.uuid(), exactUrl: z.url(), schedule: legalSourceMonitorScheduleSchema, nextCheckAt: z.coerce.date().optional() });
export const corpusMonitorUpdateSchema = z.object({ schedule: legalSourceMonitorScheduleSchema, paused: z.boolean() });
export const changeAlertResolveSchema = z.object({ resolution: z.enum(["dismiss", "create_candidate"]), reason: z.string().trim().min(1), candidateVersionLabel: z.string().optional(), language: z.string().optional() });

export const corpusFamilySchema = z.object({ id: z.uuid(), code: z.string(), frameworkCode: z.string(), jurisdictionCode: z.string(), title: z.string(), version: z.number().int().positive() }).loose();
export const legalSourceSchema = z.object({ id: z.uuid(), familyId: z.uuid(), stableCode: z.string(), title: z.string(), authorityTier: z.enum(["primary_authority", "official_guidance", "curated_secondary"]), version: z.number().int().positive() }).loose();
export const legalSourceVersionSchema = z.object({ id: z.uuid(), sourceId: z.uuid(), versionLabel: z.string(), status: z.enum(["draft", "reviewed", "published", "withdrawn"]) }).loose();
export const legalSourceRenditionSchema = z.object({ id: z.uuid(), sourceVersionId: z.uuid(), language: z.string(), translationStatus: z.enum(["official", "reviewed_internal", "machine_assisted"]), contentHash: z.string() }).loose();
export const legalProcessingGenerationSchema = z.object({ id: z.uuid(), renditionId: z.uuid(), jobId: z.uuid().nullable(), embeddingJobId: z.uuid().nullable(), generationNumber: z.number().int().positive(), state: z.enum(["queued", "running", "review_required", "reviewed", "failed", "cancelled"]) }).loose();
export const legalChunkSchema = z.object({ id: z.uuid(), generationId: z.uuid(), position: z.number().int().nonnegative(), text: z.string(), textHash: z.string() }).loose();
export const corpusReleaseSchema = z.object({ id: z.uuid(), familyId: z.uuid(), versionLabel: z.string(), status: z.enum(["draft", "published", "withdrawn"]), evaluationState: z.enum(["not_run", "pending", "passed", "failed"]), version: z.number().int().positive() }).loose();
export const corpusReleaseMemberSchema = z.object({ releaseId: z.uuid(), sourceVersionId: z.uuid(), renditionId: z.uuid(), processingGenerationId: z.uuid(), position: z.number().int().nonnegative() }).loose();
export const corpusMonitorSchema = z.object({ id: z.uuid(), sourceId: z.uuid(), exactUrl: z.url(), schedule: z.string(), active: z.boolean(), version: z.number().int().positive() }).loose();
export const changeAlertSchema = z.object({ id: z.uuid(), sourceId: z.uuid(), state: z.enum(["open", "candidate_created", "dismissed"]), version: z.number().int().positive() }).loose();
export const platformAdministratorSchema = z.object({ userId: z.uuid(), revokedAt: z.union([z.iso.datetime(), z.date()]).nullable() }).loose();
export const platformAuditEventSchema = z.object({ id: z.uuid(), eventType: z.string(), entityType: z.string(), entityId: z.uuid(), actorUserId: z.uuid().nullable(), metadata: z.unknown(), createdAt: z.iso.datetime() });
