-- One-time Drizzle v1 transition.
-- Rename constraints in place so integrity enforcement is never removed.

alter table public.ai_processing_run_artifact_inputs
  rename constraint ai_processing_run_artifact_inputs_run_id_artifact_revision_id_p
  to ai_run_artifact_inputs_pk;

alter table public.ai_processing_run_assessment_inputs
  rename constraint ai_processing_run_assessment_inputs_run_id_assessment_revision_
  to ai_run_assessment_inputs_pk;

alter table public.ai_processing_runs
  rename constraint ai_processing_runs_output_artifact_revision_id_generated_artifa
  to ai_processing_runs_output_artifact_revision_fk;

alter table public.artifact_revision_artifact_sources
  rename constraint artifact_revision_artifact_sources_artifact_revision_id_source_
  to artifact_revision_artifact_sources_pk;

alter table public.artifact_revision_assessment_sources
  rename constraint artifact_revision_assessment_sources_artifact_revision_id_asses
  to artifact_revision_assessment_sources_pk;

alter table public.artifact_revision_document_sources
  rename constraint artifact_revision_document_sources_artifact_revision_id_documen
  to artifact_revision_document_sources_pk;

alter table public.assessment_answer_options
  rename constraint assessment_answer_options_assessment_answer_id_question_option_
  to assessment_answer_options_pk;

alter table public.assessment_revisions
  rename constraint assessment_revisions_parent_revision_id_assessment_revisions_id
  to assessment_revisions_parent_fk;

alter table public.assessments
  rename constraint assessments_applicability_artifact_revision_id_generated_artifa
  to assessments_applicability_artifact_fk;

alter table public.compliance_check_release_content_revisions
  rename constraint compliance_check_release_content_revisions_check_release_id_con
  to check_release_content_revisions_pk;

alter table public.compliance_check_release_corpus_releases
  rename constraint compliance_check_release_corpus_releases_check_release_id_famil
  to check_release_corpus_releases_pk;

alter table public.compliance_check_release_fact_versions
  rename constraint compliance_check_release_fact_versions_check_release_id_fact_de
  to check_release_fact_versions_pk;

alter table public.compliance_check_release_profiles
  rename constraint compliance_check_release_profiles_check_release_id_country_code
  to check_release_profiles_pk;

alter table public.fact_options
  rename constraint fact_options_jurisdiction_entity_type_id_jurisdiction_entity_ty
  to fact_options_jurisdiction_entity_type_fk;

alter table public.gap_analysis_release_corpus_releases
  rename constraint gap_analysis_release_corpus_releases_gap_analysis_release_id_fa
  to gap_release_corpus_releases_pk;

alter table public.gap_finding_evidence
  rename constraint gap_finding_evidence_legal_source_chunk_id_legal_source_chunks_
  to gap_finding_evidence_legal_source_chunk_fk;

alter table public.gap_reassessment_draft_documents
  rename constraint gap_reassessment_draft_documents_draft_id_document_version_id_p
  to gap_reassessment_draft_documents_pk;

alter table public.gap_reassessment_drafts
  rename constraint gap_reassessment_drafts_ai_processing_run_id_ai_processing_runs
  to gap_reassessment_drafts_ai_run_fk;

alter table public.gap_requirement_set_members
  rename constraint gap_requirement_set_members_requirement_set_version_id_requirem
  to gap_requirement_set_members_pk;

alter table public.generated_artifact_revisions
  rename constraint generated_artifact_revisions_parent_revision_id_generated_artif
  to generated_artifact_revisions_parent_fk;

alter table public.guest_applicability_checks
  rename constraint guest_applicability_checks_check_release_id_compliance_check_re
  to guest_applicability_checks_release_fk;

alter table public.jurisdiction_entity_type_legal_provisions
  rename constraint jurisdiction_entity_type_legal_provisions_jurisdiction_entity_t
  to jurisdiction_entity_type_legal_provisions_pk;

alter table public.jurisdiction_profile_legal_provisions
  rename constraint jurisdiction_profile_legal_provisions_jurisdiction_profile_vers
  to jurisdiction_profile_legal_provisions_pk;

alter table public.organization_fact_value_options
  rename constraint organization_fact_value_options_organization_fact_value_id_fact
  to organization_fact_value_options_pk;

alter table public.scope_entity_type_legal_provisions
  rename constraint scope_entity_type_legal_provisions_scope_entity_type_version_id
  to scope_entity_type_legal_provisions_pk;

alter table public.scope_threshold_set_legal_provisions
  rename constraint scope_threshold_set_legal_provisions_scope_threshold_set_id_leg
  to scope_threshold_set_legal_provisions_pk;
