import {
  GAP_PROMPT_V2_NAME,
  GAP_PROMPT_V2_TEMPLATE_HASH,
  GAP_PROMPT_V2_VERSION,
  GAP_RESPONSE_SCHEMA_V2_VERSION,
} from "../../prompt-contract-v2";
import type { GapAnalysisReleaseDefinition } from "../types";

const options = [
  { stableValue: "implemented_documented", position: 10, label: { de: "Umgesetzt und dokumentiert", en: "Implemented and documented" } },
  { stableValue: "partially_implemented", position: 20, label: { de: "Teilweise umgesetzt", en: "Partially implemented" } },
  { stableValue: "not_implemented", position: 30, label: { de: "Nicht umgesetzt", en: "Not implemented" } },
  { stableValue: "unknown", position: 40, label: { de: "Unbekannt", en: "Unknown" } },
] as const;

const legalReference = (code: string) => [{
  label: {
    de: `Demo-Platzhalter – NIS2-Bezug ${code}`,
    en: `Demo placeholder – NIS2 reference ${code}`,
  },
  url: "https://eur-lex.europa.eu/eli/dir/2022/2555/oj",
  demoPlaceholder: true as const,
}];

export const demoGapRelease: GapAnalysisReleaseDefinition = {
  releaseCode: "nis2-gap",
  versionLabel: "demo-v1",
  title: { de: "NIS2-Gap-Analyse (Demo)", en: "NIS2 gap analysis (demo)" },
  compatibleCheck: { checkCode: "nis2_applicability", versionLabel: "2026-v1" },
  requiredCorpusFamilies: ["nis2-eu-primary", "nis2-de-primary"],
  defaultLocale: "de",
  prompt: {
    name: GAP_PROMPT_V2_NAME,
    version: GAP_PROMPT_V2_VERSION,
    templateHash: GAP_PROMPT_V2_TEMPLATE_HASH,
    responseSchemaVersion: GAP_RESPONSE_SCHEMA_V2_VERSION,
  },
  evaluator: { kind: "gap_evidence_v1", version: 1 },
  modelPolicy: {
    provider: "openai",
    model: "gpt-5-mini",
    maxRequirementsPerBatch: 4,
  },
  questionnaire: {
    code: "nis2-gap-demo",
    title: { de: "NIS2-Gap-Analyse (Demo)", en: "NIS2 gap analysis (demo)" },
    questions: [
      {
        stableKey: "gap.access_control",
        position: 10,
        text: { de: "Sind Zugriffsrechte definiert, regelmäßig geprüft und dokumentiert?", en: "Are access rights defined, reviewed regularly, and documented?" },
        help: { de: "Bewerten Sie Rollen, Freigaben und regelmäßige Rezertifizierungen.", en: "Consider roles, approvals, and periodic recertification." },
        required: true,
        answerType: "single_choice",
        options: [...options],
      },
      {
        stableKey: "gap.backup_recovery",
        position: 20,
        text: { de: "Werden Backups erstellt und Wiederherstellungen regelmäßig getestet?", en: "Are backups created and restores tested regularly?" },
        help: { de: "Berücksichtigen Sie Häufigkeit, Schutz und dokumentierte Tests.", en: "Consider frequency, protection, and documented restore tests." },
        required: true,
        answerType: "single_choice",
        options: [...options],
      },
      {
        stableKey: "gap.incident_response",
        position: 30,
        text: { de: "Existiert ein dokumentierter und erprobter Prozess für Sicherheitsvorfälle?", en: "Is there a documented and exercised security incident process?" },
        help: { de: "Berücksichtigen Sie Erkennung, Eskalation, Meldung und Übungen.", en: "Consider detection, escalation, reporting, and exercises." },
        required: true,
        answerType: "single_choice",
        options: [...options],
      },
      {
        stableKey: "gap.supply_chain",
        position: 40,
        text: { de: "Werden Cybersicherheitsrisiken bei Lieferanten bewertet und nachverfolgt?", en: "Are supplier cybersecurity risks assessed and tracked?" },
        help: { de: "Berücksichtigen Sie Auswahl, Verträge, Nachweise und laufende Überwachung.", en: "Consider selection, contracts, evidence, and ongoing monitoring." },
        required: true,
        answerType: "single_choice",
        options: [...options],
      },
    ],
  },
  requirementSet: {
    code: "nis2-security-demo",
    title: "NIS2 security requirements – demo only",
    versionLabel: "demo-v1",
    requirements: [
      {
        code: "DEMO-AC-01",
        versionLabel: "demo-v1",
        position: 10,
        criticality: "high",
        title: { de: "Zugriffskontrolle", en: "Access control" },
        requirementText: { de: "Die Organisation steuert und überprüft Zugriffsrechte nachvollziehbar.", en: "The organization controls and reviews access rights traceably." },
        recommendation: { de: "Rollenmodell, Freigaben und Rezertifizierung dokumentieren.", en: "Document the role model, approvals, and recertification." },
        legalReferences: legalReference("Art. 21"),
        questionStableKeys: ["gap.access_control"],
        applicableOutcomeCodes: ["essential_entity", "important_entity"],
      },
      {
        code: "DEMO-BC-01",
        versionLabel: "demo-v1",
        position: 20,
        criticality: "critical",
        title: { de: "Backup und Wiederherstellung", en: "Backup and recovery" },
        requirementText: { de: "Die Organisation sichert kritische Daten und testet Wiederherstellungen.", en: "The organization backs up critical data and tests restoration." },
        recommendation: { de: "Backup-Plan, Schutzmaßnahmen und Wiederherstellungstests nachweisen.", en: "Evidence the backup plan, safeguards, and restore tests." },
        legalReferences: legalReference("Art. 21"),
        questionStableKeys: ["gap.backup_recovery"],
        applicableOutcomeCodes: ["essential_entity", "important_entity"],
      },
      {
        code: "DEMO-IR-01",
        versionLabel: "demo-v1",
        position: 30,
        criticality: "critical",
        title: { de: "Reaktion auf Sicherheitsvorfälle", en: "Incident response" },
        requirementText: { de: "Die Organisation erkennt, behandelt und meldet Sicherheitsvorfälle nach einem erprobten Prozess.", en: "The organization detects, handles, and reports incidents through an exercised process." },
        recommendation: { de: "Incident-Response-Plan, Rollen und Übungsnachweise pflegen.", en: "Maintain an incident response plan, roles, and exercise evidence." },
        legalReferences: legalReference("Art. 21/23"),
        questionStableKeys: ["gap.incident_response"],
        applicableOutcomeCodes: ["essential_entity", "important_entity"],
      },
      {
        code: "DEMO-SC-01",
        versionLabel: "demo-v1",
        position: 40,
        criticality: "high",
        title: { de: "Lieferkettensicherheit", en: "Supply-chain security" },
        requirementText: { de: "Die Organisation bewertet und behandelt Cybersicherheitsrisiken ihrer Lieferanten.", en: "The organization assesses and treats supplier cybersecurity risks." },
        recommendation: { de: "Lieferantenkriterien, Vertragsanforderungen und Überwachung dokumentieren.", en: "Document supplier criteria, contractual requirements, and monitoring." },
        legalReferences: legalReference("Art. 21"),
        questionStableKeys: ["gap.supply_chain"],
        applicableOutcomeCodes: ["essential_entity", "important_entity"],
      },
    ],
  },
};
